name: Build

on:
  push:
    branches: [ '*' ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    container: docker://hhmhh/weylus_build:latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: deps/dist*
        key: ${{ runner.os }}-deps-${{ hashFiles('deps/*') }}
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
    - name: Build
      run: ./docker_build.sh
      shell: bash
    - name: Artifacts1
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: packages/weylus-linux.zip
    - name: Artifacts2
      uses: actions/upload-artifact@v2
      with:
        name: linux-deb
        path: packages/Weylus*.deb
    - name: Artifacts3
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: packages/weylus-windows.zip
    - name: Publish
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            packages/weylus-linux.zip
            packages/Weylus*.deb
            packages/weylus-windows.zip
          prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
